apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  namespace: deep-dive-kafka
  name: kafka-source-feedback
  labels:
    kafkasources.sources.knative.dev/key-type: int
spec:
  net:
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: kafka-config
          key: kafka.user.name
      type:
        secretKeyRef:
          name: kafka-config
          key: kafka.user.sasl.type
      password:
        secretKeyRef:
          name: feedback-user
          key: password
    tls:
      enable: false
      caCert:
        secretKeyRef:
          name: deep-dive-kafka-cluster-ca-cert
          key: ca.crt
  consumerGroup: feedback-persistence
  bootstrapServers:
    - deep-dive-kafka-kafka-bootstrap.deep-dive-kafka.svc.cluster.local:9092
  topics:
    - feedback-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: feedback-persistence
    uri: /feedback