apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: feedback-persistence-pipeline-run-
  namespace: deep-dive-quarkus
spec:
  params:
    - name: git-url
      value: 'https://github.com/marcoklaassen/deep-dive-serverless-feedback-persistence'
    - name: git-revision
      value: quarkus-deep-dive-2
    - name: IMAGE
      value: >-
        image-registry.openshift-image-registry.svc:5000/deep-dive-quarkus/feedback-persistence
    - name: APPVERSION
      value: latest
  pipelineRef:
    name: quarkus-native-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi